# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  encoding: utf8
  database: reservester_development
  username: root
  password: password
  host: 127.0.0.1
  port: 3306
test:
  adapter: sqlite3
  encoding: utf8
  database: reservester_test
  username: root
  password: password
  host: 127.0.0.1
  port: 3306
production:
  adapter: postgresql
  encoding: unicode
  database: reservester_production
  pool: 5
  username: root
  password: password